name: Check for unsafe catalog updates
"on":
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions:
  contents: read

jobs:
  check_catalog_correctly_updated:
    name: Check updates to latest-dev and reverse-dev are properly handled by PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install pglast
        run: |
          python -m pip install pglast
      - name: Check latest-dev contents
        shell: bash {0}
        id: check_latestdev
        run: |
          if ! python scripts/check_updates_ast.py "sql/updates/latest-dev.sql"; then
            exit 1
          fi
          exit 0
      - name: Check reverse-dev contents
        if: always()
        shell: bash {0}
        run: |
          if ! python scripts/check_updates_ast.py "sql/updates/reverse-dev.sql"; then
            exit 1
          fi
          exit 0
