# Ignoring version of the corresponding workflow. These files are
# needed to run required workflows even when the real workflow is not
# executed because some files were ignored.
name: Regression Linux i386
"on":
  push:
    branches:
      - main
    paths:
      - '!**'
      - '**.md'
      - 'LICENSE*'
      - NOTICE
  pull_request:
    paths:
      - '!**'
      - '**.md'
      - 'LICENSE*'
      - NOTICE
permissions:
  contents: read

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      pg_latest: ${{ steps.setter.outputs.PG_LATEST }}
      pg16_latest: ${{ steps.setter.outputs.PG16_LATEST }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - name: Checkout source code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Read configuration
      id: setter
      run: python .github/gh_config_reader.py

  regress_linux_32bit:
    name: PG${{ matrix.pg }} ${{ matrix.build_type }} linux-i386
    runs-on: ubuntu-latest
    needs: config
    strategy:
      matrix:
        pg: ${{ fromJson(needs.config.outputs.pg_latest) }}
        build_type: [ Debug ]
        include:
          - pg: ${{ fromJson(needs.config.outputs.pg16_latest) }}
            build_type: Debug
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - run: |
          echo "No build required"
