# Ignoring version of the corresponding workflow. These files are
# needed to run required workflows even when the real workflow is not
# executed because some files were ignored.
name: Shellcheck
"on":
  push:
    branches:
      - main
    paths-ignore:
      - '**.sh'
      - .github/workflows/shellcheck.yaml
  pull_request:
    paths-ignore:
      - '**.sh'
      - .github/workflows/shellcheck.yaml
permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "No build required"
