# Ignoring version of the corresponding workflow. These files are
# needed to run required workflows even when the real workflow is not
# executed because some files were ignored.
name: Regression Windows
"on":
  push:
    branches:
      - main
    paths:
      - '!**'
      - '**.md'
      - CHANGELOG
      - 'LICENSE*'
      - NOTICE
      - 'bootstrap*'
  pull_request:
    paths:
      - '!**'
      - '**.md'
      - CHANGELOG
      - 'LICENSE*'
      - NOTICE
      - 'bootstrap*'
permissions:
  contents: read

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      build_type: ${{ steps.build_type.outputs.build_type }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - name: Checkout source code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set build_type
      id: build_type
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "build_type=['Debug']" >>$GITHUB_OUTPUT
        else
          echo "build_type=['Debug','Release']" >>$GITHUB_OUTPUT
        fi
  build:
    name: PG${{ matrix.pg }} ${{ matrix.build_type }} ${{ matrix.os }}
    runs-on: ubuntu-latest
    needs: config
    strategy:
      fail-fast: false
      matrix:
        pg: [ 14, 15, 16 ]
        os: [ windows-2022 ]
        build_type: ${{ fromJson(needs.config.outputs.build_type) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - run: |
          echo "No build required"
